"""Provider-independent ContextForge domain primitives."""

from contextforge.domain.fingerprints import (
    ConfigurationFingerprint,
    ContentFingerprint,
    FingerprintOrdering,
    LineEndingPolicy,
    ProjectFingerprint,
    ProposalFingerprint,
    fingerprint_configuration,
    fingerprint_content,
    fingerprint_project,
    fingerprint_proposal,
)
from contextforge.domain.identifiers import (
    ApprovalId,
    ContextBundleId,
    ExecutionId,
    IndexId,
    InferenceRequestId,
    InferenceResponseId,
    InventoryId,
    PatchProposalId,
    ProjectId,
    RetrievalId,
    TaskId,
    new_approval_id,
    new_context_bundle_id,
    new_execution_id,
    new_index_id,
    new_inference_request_id,
    new_inference_response_id,
    new_inventory_id,
    new_patch_proposal_id,
    new_project_id,
    new_retrieval_id,
    new_task_id,
)
from contextforge.domain.tasks import RequestedOutput, TaskKind, TaskSpecification

__all__ = [
    "ApprovalId",
    "ConfigurationFingerprint",
    "ContentFingerprint",
    "ContextBundleId",
    "ExecutionId",
    "FingerprintOrdering",
    "IndexId",
    "InferenceRequestId",
    "InferenceResponseId",
    "InventoryId",
    "LineEndingPolicy",
    "PatchProposalId",
    "ProjectFingerprint",
    "ProjectId",
    "ProposalFingerprint",
    "RequestedOutput",
    "RetrievalId",
    "TaskId",
    "TaskKind",
    "TaskSpecification",
    "fingerprint_configuration",
    "fingerprint_content",
    "fingerprint_project",
    "fingerprint_proposal",
    "new_approval_id",
    "new_context_bundle_id",
    "new_execution_id",
    "new_index_id",
    "new_inference_request_id",
    "new_inference_response_id",
    "new_inventory_id",
    "new_patch_proposal_id",
    "new_project_id",
    "new_retrieval_id",
    "new_task_id",
]
