"""Tests for CF-014 increment I019 deterministic artifact classification."""

import pytest

from contextforge.domain import ArtifactPath
from contextforge.scanner import (
    MAX_CLASSIFICATION_SAMPLE_BYTES,
    ArtifactClassification,
    ArtifactKind,
    ClassificationResult,
    DeterministicArtifactClassifier,
    TraversalEntry,
    TraversalEntryType,
)


def classify(
    path: str,
    sample: bytes = b"",
    *,
    entry_type: TraversalEntryType = TraversalEntryType.FILE,
) -> ClassificationResult:
    entry = TraversalEntry(ArtifactPath(path), entry_type, len(sample))
    return DeterministicArtifactClassifier().classify(entry, sample)


def test_python_source_is_detected_from_extension() -> None:
    result = classify("src/contextforge/main.py", b'print("hello")\n')

    assert result.kind is ArtifactKind.SOURCE
    assert result.classifications == (ArtifactClassification.SOURCE,)
    assert result.detected_language == "python"
    assert result.encoding == "utf-8"


@pytest.mark.parametrize(
    "path",
    [
        "tests/test_service.py",
        "src/service_test.py",
        "src/service.spec.ts",
    ],
)
def test_test_files_preserve_source_and_test_classifications(path: str) -> None:
    result = classify(path, b"test content")

    assert result.kind is ArtifactKind.TEST
    assert result.classifications == (
        ArtifactClassification.SOURCE,
        ArtifactClassification.TEST,
    )
    assert result.detected_language is not None


@pytest.mark.parametrize(
    "path",
    [
        "README.md",
        "docs/architecture.rst",
        "CHANGELOG",
        "LICENSE.txt",
    ],
)
def test_readme_and_documentation_files_are_detected(path: str) -> None:
    result = classify(path, b"documentation")

    assert result.kind is ArtifactKind.DOCUMENTATION
    assert ArtifactClassification.DOCUMENTATION in result.classifications


@pytest.mark.parametrize(
    "path",
    [
        ".env",
        ".env.production",
        "config/credentials.json",
        "certificates/private.key",
        "id_rsa",
    ],
)
def test_secret_like_paths_are_sensitive_without_exposing_values(path: str) -> None:
    secret = b"password=do-not-expose"

    result = classify(path, secret)

    assert ArtifactClassification.SENSITIVE in result.classifications
    assert "do-not-expose" not in repr(result)


@pytest.mark.parametrize(
    "path",
    [
        "pyproject.toml",
        "package-lock.json",
        "poetry.lock",
        "Cargo.lock",
        "uv.lock",
    ],
)
def test_manifests_and_lockfiles_are_detected(path: str) -> None:
    result = classify(path, b"manifest")

    assert result.kind is ArtifactKind.MANIFEST
    assert result.classifications == (ArtifactClassification.CONFIGURATION,)


@pytest.mark.parametrize(
    "path",
    [
        "assets/logo.png",
        "dist/archive.zip",
        "bin/application.exe",
        "docs/manual.pdf",
    ],
)
def test_known_binary_extensions_do_not_require_content_read(path: str) -> None:
    result = classify(path)

    assert result.kind is ArtifactKind.BINARY
    assert ArtifactClassification.BINARY in result.classifications
    assert result.encoding is None


def test_nul_byte_in_bounded_sample_detects_binary() -> None:
    result = classify("data/unknown.dat", b"text\x00binary")

    assert result.kind is ArtifactKind.BINARY
    assert result.classifications == (ArtifactClassification.BINARY,)


@pytest.mark.parametrize(
    "path",
    [
        "web/app.min.js",
        "web/app.bundle.css",
        "generated/client.py",
        "dist/application.js",
    ],
)
def test_generated_bundles_and_directories_are_detected(path: str) -> None:
    result = classify(path, b"generated source")

    assert result.kind is ArtifactKind.GENERATED
    assert ArtifactClassification.GENERATED in result.classifications


def test_generated_header_is_detected_from_bounded_sample() -> None:
    result = classify("src/client.go", b"// Code generated by tool. DO NOT EDIT.\n")

    assert result.kind is ArtifactKind.GENERATED
    assert "bounded_sample:generated" in result.evidence
    assert result.detected_language == "go"


def test_private_key_header_is_sensitive_without_evidence_content() -> None:
    result = classify(
        "certificates/server",
        b"-----BEGIN PRIVATE KEY-----\nprivate-material\n",
    )

    assert ArtifactClassification.SENSITIVE in result.classifications
    assert "private-material" not in repr(result)


def test_utf16_bom_is_text_not_binary() -> None:
    sample = b"\xff\xfe" + "documentation".encode("utf-16-le")
    result = classify("notes.txt", sample)

    assert result.kind is ArtifactKind.DOCUMENTATION
    assert result.encoding == "utf-16-le"


def test_inspection_never_uses_bytes_beyond_bound() -> None:
    sample = b"a" * MAX_CLASSIFICATION_SAMPLE_BYTES + b"\x00"
    result = classify("src/module.py", sample)

    assert result.kind is ArtifactKind.SOURCE
    assert ArtifactClassification.BINARY not in result.classifications


def test_directory_requires_no_content_classification() -> None:
    result = classify("src", entry_type=TraversalEntryType.DIRECTORY)

    assert result.kind is ArtifactKind.DIRECTORY
    assert result.classifications == (ArtifactClassification.UNKNOWN,)


def test_unknown_file_has_explicit_unknown_classification() -> None:
    result = classify("data/artifact", b"ordinary text")

    assert result.kind is ArtifactKind.UNKNOWN
    assert result.classifications == (ArtifactClassification.UNKNOWN,)


def test_classification_is_deterministic() -> None:
    first = classify("tests/test_main.py", b"def test_value(): pass\n")
    second = classify("tests/test_main.py", b"def test_value(): pass\n")

    assert first == second
