"""Context Retriever Core contracts."""

from contextforge.retrieval.budgeting import (
    CONTEXT_BUDGET_PLANNER_VERSION,
    BudgetSelectionResult,
    BudgetUsage,
    CandidateBudgetEstimate,
    ContextBudgetPlanner,
    ContextBudgetReservation,
)
from contextforge.retrieval.closure import (
    DEPENDENCY_CLOSURE_POLICY_VERSION,
    ClosureAddition,
    DependencyClosureConfig,
    DependencyClosurePolicy,
    DependencyClosureResult,
)
from contextforge.retrieval.dependencies import (
    DEPENDENCY_TRAVERSAL_STRATEGY_VERSION,
    DependencyTraversalConfig,
    DependencyTraversalPath,
    DependencyTraversalResult,
    DependencyTraversalStep,
    DependencyTraversalStrategy,
)
from contextforge.retrieval.eligibility import (
    ELIGIBILITY_FILTER_VERSION,
    ArtifactEligibilityRecord,
    CandidateEligibilityFilter,
    EligibilityFilterResult,
    EligibilityPolicy,
    GeneratedArtifactPolicy,
    ProviderDeliveryMode,
)
from contextforge.retrieval.explicit import (
    EXPLICIT_REFERENCE_STRATEGY_VERSION,
    ExplicitReferenceKind,
    ExplicitReferenceResolution,
    ExplicitReferenceResult,
    ExplicitReferenceStrategy,
    ExplicitResolutionState,
)
from contextforge.retrieval.lexical import (
    LEXICAL_SEARCH_STRATEGY_VERSION,
    LexicalSearchResult,
    LexicalSearchStrategy,
)
from contextforge.retrieval.models import (
    CandidateEligibility,
    CandidateOutcome,
    CandidateType,
    ContextBudget,
    RetrievalCandidate,
    RetrievalEvidence,
    RetrievalRequest,
    RetrievalResult,
    RetrievalStatistics,
    RetrievalStatus,
    SelectedContextItem,
    SelectionDecision,
    SelectionRationale,
    SelectionReason,
)
from contextforge.retrieval.ports import ContextRetriever
from contextforge.retrieval.query import (
    TASK_QUERY_NORMALIZER_VERSION,
    NormalizedTaskQuery,
    QueryTerm,
    QueryTermKind,
    TaskQueryNormalizer,
)
from contextforge.retrieval.result import (
    RETRIEVAL_RESULT_ASSEMBLER_VERSION,
    RetrievalResultAssembler,
)
from contextforge.retrieval.scoring import (
    RETRIEVAL_SCORING_MODEL_VERSION,
    CandidateScore,
    RetrievalScoreResult,
    RetrievalScoringConfig,
    RetrievalScoringModel,
    ScoreComponent,
    ScoreContribution,
)
from contextforge.retrieval.simple_retriever import (
    SIMPLE_RETRIEVER_VERSION,
    SimpleContextRetriever,
)
from contextforge.retrieval.structural import (
    STRUCTURAL_RETRIEVAL_STRATEGY_VERSION,
    StructuralRetrievalStrategy,
    StructuralRole,
    StructuralSearchResult,
)

__all__ = [
    "CONTEXT_BUDGET_PLANNER_VERSION",
    "DEPENDENCY_CLOSURE_POLICY_VERSION",
    "DEPENDENCY_TRAVERSAL_STRATEGY_VERSION",
    "ELIGIBILITY_FILTER_VERSION",
    "EXPLICIT_REFERENCE_STRATEGY_VERSION",
    "LEXICAL_SEARCH_STRATEGY_VERSION",
    "RETRIEVAL_RESULT_ASSEMBLER_VERSION",
    "RETRIEVAL_SCORING_MODEL_VERSION",
    "SIMPLE_RETRIEVER_VERSION",
    "STRUCTURAL_RETRIEVAL_STRATEGY_VERSION",
    "TASK_QUERY_NORMALIZER_VERSION",
    "ArtifactEligibilityRecord",
    "BudgetSelectionResult",
    "BudgetUsage",
    "CandidateBudgetEstimate",
    "CandidateEligibility",
    "CandidateEligibilityFilter",
    "CandidateOutcome",
    "CandidateScore",
    "CandidateType",
    "ClosureAddition",
    "ContextBudget",
    "ContextBudgetPlanner",
    "ContextBudgetReservation",
    "ContextRetriever",
    "DependencyClosureConfig",
    "DependencyClosurePolicy",
    "DependencyClosureResult",
    "DependencyTraversalConfig",
    "DependencyTraversalPath",
    "DependencyTraversalResult",
    "DependencyTraversalStep",
    "DependencyTraversalStrategy",
    "EligibilityFilterResult",
    "EligibilityPolicy",
    "ExplicitReferenceKind",
    "ExplicitReferenceResolution",
    "ExplicitReferenceResult",
    "ExplicitReferenceStrategy",
    "ExplicitResolutionState",
    "GeneratedArtifactPolicy",
    "LexicalSearchResult",
    "LexicalSearchStrategy",
    "NormalizedTaskQuery",
    "ProviderDeliveryMode",
    "QueryTerm",
    "QueryTermKind",
    "RetrievalCandidate",
    "RetrievalEvidence",
    "RetrievalRequest",
    "RetrievalResult",
    "RetrievalResultAssembler",
    "RetrievalScoreResult",
    "RetrievalScoringConfig",
    "RetrievalScoringModel",
    "RetrievalStatistics",
    "RetrievalStatus",
    "ScoreComponent",
    "ScoreContribution",
    "SelectedContextItem",
    "SelectionDecision",
    "SelectionRationale",
    "SelectionReason",
    "SimpleContextRetriever",
    "StructuralRetrievalStrategy",
    "StructuralRole",
    "StructuralSearchResult",
    "TaskQueryNormalizer",
]
