"""Application-layer ports and orchestration contracts."""

from contextforge.application.analysis import (
    AnalysisExecutionPipeline,
    AnalysisExecutionResult,
    AnalysisPipelineError,
    ContextBundleBuilder,
    ProviderNotFoundError,
    ProviderRegistry,
)
from contextforge.application.indexing import (
    InventoryNotFoundError,
    InventoryStorage,
    ProjectIndexBuild,
    ProjectScan,
)
from contextforge.application.initialization import (
    ProjectInitialization,
    ProjectInitializationPort,
    ProjectInitializationResult,
)
from contextforge.application.messages import (
    ApplicationCommand,
    ApplicationQuery,
    ApplyPatchProposal,
    ApprovePatchProposal,
    BuildProjectIndex,
    CheckProviderHealth,
    ExecuteTask,
    GetContextBundle,
    GetEffectiveConfiguration,
    GetPatchProposal,
    GetProjectStatus,
    GetPromptPreview,
    InitializeProject,
    ListProviders,
    RejectPatchProposal,
    ScanProject,
)
from contextforge.application.patches import (
    ApplicationPreviewChange,
    PatchApplication,
    PatchApplicationPreview,
    PatchApplicationResult,
    PatchApplicationStatus,
)
from contextforge.application.preflight import (
    ApplicationPreflightEvidence,
    ApplicationPreflightResult,
    PatchApplicationPreflight,
)

__all__ = [
    "AnalysisExecutionPipeline",
    "AnalysisExecutionResult",
    "AnalysisPipelineError",
    "ApplicationCommand",
    "ApplicationPreflightEvidence",
    "ApplicationPreflightResult",
    "ApplicationPreviewChange",
    "ApplicationQuery",
    "ApplyPatchProposal",
    "ApprovePatchProposal",
    "BuildProjectIndex",
    "CheckProviderHealth",
    "ContextBundleBuilder",
    "ExecuteTask",
    "GetContextBundle",
    "GetEffectiveConfiguration",
    "GetPatchProposal",
    "GetProjectStatus",
    "GetPromptPreview",
    "InitializeProject",
    "InventoryNotFoundError",
    "InventoryStorage",
    "ListProviders",
    "PatchApplication",
    "PatchApplicationPreflight",
    "PatchApplicationPreview",
    "PatchApplicationResult",
    "PatchApplicationStatus",
    "ProjectIndexBuild",
    "ProjectInitialization",
    "ProjectInitializationPort",
    "ProjectInitializationResult",
    "ProjectScan",
    "ProviderNotFoundError",
    "ProviderRegistry",
    "RejectPatchProposal",
    "ScanProject",
]
